filenames:
  - {{ crowdsec_logs }}/traefik.log
  - {{ crowdsec_logs }}/access.log
labels:
  type: traefik
---
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
filenames:
  - {{ crowdsec_logs }}/authelia.log
labels:
  type: authelia