- name: Install Crowdsec
  tags: crowdsec
  block:
    - name: Create working directory
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Move files
      template:
        src: acquis.yaml
        dest: "{{ work_dir }}"


    - name: Start Crowdsec
      docker_container:
        name: crowdsec
        image: "crowdsecurity/crowdsec:{{ version }}"
        state: started
        recreate: yes
        restart_policy: unless-stopped
        exposed_ports:
          - "8080"
        volumes:
          - "{{ work_dir }}:/etc/crowdsec"
          - "{{ work_dir }}/acquis.yaml:/etc/crowdsec/acquis.yaml"
          - "{{ work_dir }}/data:/var/lib/crowdsec/data"
          - "{{ auth_log }}:{{ auth_log }}:ro"
          - "{{ crowdsec_logs }}:{{ crowdsec_logs }}:ro"
        env:
          TZ: "Europe/Brussels"
          PGUID: "1000"
          PGID: "1000"
          COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/http-cve LePresidente/authelia crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/sshd"
        networks:
          - name: "{{ traefik_net }}"
            ipv4_address: "{{ crowdsec_ip }}"

    - name: Automate hub update
      cron:
        name: hub update
        minute: "0"
        hour: "6"
        job: "docker exec crowdsec cscli hub update && docker exec crowdsec cscli hub upgrade"
