work_dir: "/opt/traefik/"
version: "v2.8.1"
socket_net: # example: 192.168.7.0/24
logs: "{{ work_dir }}/logs"
traefik_subnet: #example: 192.168.8.0/24
traefik_ip:
socket_subnet:
subdomain: "traefik.{{ domain }}"