- name: Uptime Kuma
  tags: uptime
  block:

    - name: Install uptime
      docker_container:
        name: uptime
        image: "louislam/uptime-kuma:{{ version }}"
        state: started
        recreate: yes
        restart_policy: unless-stopped
        volumes:
          - "uptime-kuma:/app/data"
        networks:
          - name: "{{ traefik_net }}"
            ipv4_address: "{{ uptime_ip}}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.kuma.entryPoints: "websecure"
          traefik.http.routers.kuma.rule: "Host(`{{ subdomain }}`)"
          traefik.http.routers.kuma.tls.certresolver: "letsencrypt"
          traefik.http.services.kuma.loadBalancer.server.port: "3001"
          traefik.http.routers.kuma.middlewares: authelia@file 
